services:
  - type: web
    name: v-social-p
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    disk:
      name: vp-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.sfkeodbjvkvuphylgatc:UVOempGPz5X0Msmw@aws-1-eu-central-1.pooler.supabase.com:6543/postgres
      - key: JWT_SECRET
        generateValue: true
      - key: DB_ENCRYPTION_KEY
        generateValue: true
      - key: DATA_DIR
        value: /var/data
